# ============================================================
# BARE Pattern Card
# ============================================================
# Minimal processing - fastest execution
# Use for: Simple queries, speed-critical applications

name: "bare"
display_name: "⚡ Bare Mode"
description: "Minimal processing for maximum speed. Uses only essential features."
version: "1.0"

# ============================================================
# MATH CAPABILITIES
# ============================================================
math:
  # Semantic calculus - DISABLED for speed
  semantic_calculus:
    enabled: false

  # Spectral embedding - minimal
  spectral_embedding:
    enabled: true
    scales: [96]  # Single scale only
    fusion_mode: "simple"

  # Motif detection - regex only
  motif_detection:
    enabled: true
    mode: "regex"  # No NLP overhead
    patterns: ["question", "causality"]

  # Policy engine - simple
  policy_engine:
    enabled: true
    type: "neural_bandit"
    strategy: "epsilon_greedy"
    epsilon: 0.1

# ============================================================
# MEMORY CONFIGURATION
# ============================================================
memory:
  backend: "networkx"

  caching:
    vector_cache: false  # Skip for speed
    cache_size: 1000

  retrieval:
    max_shards: 5  # Minimal context
    similarity_threshold: 0.75

  graph:
    max_depth: 1  # Single hop only

# ============================================================
# TOOLS
# ============================================================
tools:
  enabled:
    - "summarize"
    - "search"

  disabled:
    - "analyze"
    - "extract"
    - "deep_research"
    - "synthesis"

  configs:
    summarize:
      max_length: 200
    search:
      max_results: 3

# ============================================================
# PERFORMANCE PROFILE
# ============================================================
performance:
  target_latency_ms: 50
  max_latency_ms: 100
  timeout_ms: 1000

  optimization:
    jit_compile: true
    parallel_threads: 2
    batch_size: 16

# ============================================================
# EXTENSIONS
# ============================================================
extensions:
  narrative_depth:
    enabled: false

  semantic_monitoring:
    enabled: false
