version: '3.8'

services:
  # Neo4j - Graph Database
  neo4j:
    image: neo4j:5.15.0
    container_name: hololoom-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/hololoom123
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_memory_heap_initial__size=512M
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - hololoom
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "hololoom123", "RETURN 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Qdrant - Vector Database
  qdrant:
    image: qdrant/qdrant:v1.7.4
    container_name: hololoom-qdrant
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC API
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - hololoom
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:6333/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  qdrant_data:
    driver: local

networks:
  hololoom:
    driver: bridge