"""
Algebraic Number Theory for HoloLoom Warp Drive
=================================================

Number fields, algebraic integers, and class groups.

A number field K = ℚ(α) is a finite extension of the rationals,
generated by a root α of an irreducible polynomial f(x) ∈ ℚ[x].

Key objects:
- Ring of integers O_K: integral closure of ℤ in K
- Discriminant Δ_K: measures ramification of primes
- Class group Cl(K): measures failure of unique factorization
- Class number h_K = |Cl(K)|: h_K = 1 iff O_K is a PID (UFD)

Applications: cryptography, coding theory, Diophantine equations.

Author: HoloLoom Team
Date: 2026-03-19
"""

import logging

import numpy as np

logger = logging.getLogger(__name__)


# ============================================================================
# NUMBER FIELD
# ============================================================================

class NumberField:
    """
    Number field K = ℚ[x]/(f(x)) where f is irreducible over ℚ.

    Elements are polynomials in α (a root of f) of degree < deg(f).
    Arithmetic: polynomial arithmetic modulo f.
    """

    def __init__(self, min_poly: np.ndarray, name: str = "K"):
        """
        Args:
            min_poly: Coefficients of the minimal polynomial [a₀, a₁, ..., aₙ]
                      representing a₀ + a₁x + ... + aₙxⁿ. Must be monic (aₙ = 1).
            name: Field name.
        """
        self.min_poly = np.array(min_poly, dtype=float)
        self._degree = len(min_poly) - 1
        self.name = name

        # Normalize to monic
        if abs(self.min_poly[-1]) > 1e-14:
            self.min_poly = self.min_poly / self.min_poly[-1]

        # Compute roots (embeddings into ℂ)
        # np.roots expects highest degree first
        self._roots = np.roots(self.min_poly[::-1])

        logger.info(f"NumberField {name} = Q[x]/(f), degree={self._degree}")

    def degree(self) -> int:
        """[K : ℚ] = degree of the minimal polynomial."""
        return self._degree

    def embeddings(self) -> np.ndarray:
        """
        All embeddings σ: K → ℂ.

        Each root of the minimal polynomial gives an embedding.
        Returns array of complex roots.
        """
        return self._roots.copy()

    def signature(self) -> tuple[int, int]:
        """
        Signature (r₁, r₂) where:
        r₁ = number of real embeddings
        r₂ = number of pairs of complex conjugate embeddings
        n = r₁ + 2r₂
        """
        real_roots = sum(1 for r in self._roots if abs(r.imag) < 1e-10)
        complex_pairs = (self._degree - real_roots) // 2
        return real_roots, complex_pairs

    def discriminant(self) -> float:
        """
        Discriminant Δ_K = Π_{i<j} (αᵢ - αⱼ)².

        The discriminant measures how far O_K is from being ℤⁿ.
        Primes dividing Δ_K are exactly the ramified primes.
        """
        n = self._degree
        disc = 1.0
        for i in range(n):
            for j in range(i + 1, n):
                diff = self._roots[i] - self._roots[j]
                disc *= diff * diff

        # Should be rational (up to sign and leading coefficient)
        return float(np.real(disc))

    def ring_of_integers(self) -> 'RingOfIntegers':
        """
        Compute the ring of integers O_K.

        For quadratic fields Q(√d), O_K = ℤ[√d] if d ≡ 2, 3 (mod 4)
        and O_K = ℤ[(1+√d)/2] if d ≡ 1 (mod 4).

        For general fields, we return the power basis approximation
        O_K ≈ ℤ[α] (which equals O_K for monogenic fields).
        """
        return RingOfIntegers(self)

    def multiply_elements(self, a: np.ndarray, b: np.ndarray) -> np.ndarray:
        """
        Multiply two elements of K (given as polynomial coefficients mod f).

        a, b are arrays of length degree, representing
        a₀ + a₁α + ... + a_{n-1}α^{n-1}.
        """
        # Polynomial multiplication
        product = np.convolve(a, b)

        # Reduce modulo minimal polynomial
        return self._reduce(product)

    def _reduce(self, poly: np.ndarray) -> np.ndarray:
        """Reduce polynomial modulo the minimal polynomial."""
        n = self._degree
        result = poly.copy()

        while len(result) > n:
            if abs(result[-1]) < 1e-14:
                result = result[:-1]
                continue
            # Subtract leading_coeff * x^(deg-n) * min_poly
            lead = result[-1]
            deg = len(result) - 1
            shift = deg - n
            for i in range(n + 1):
                if shift + i < len(result):
                    result[shift + i] -= lead * self.min_poly[i]
            result = result[:max(n, len(result) - 1)]

        # Pad to length n
        if len(result) < n:
            result = np.concatenate([result, np.zeros(n - len(result))])

        return result[:n]

    def norm_element(self, a: np.ndarray) -> float:
        """
        Norm N_{K/ℚ}(a) = Π σᵢ(a) over all embeddings.
        """
        norm = 1.0
        for root in self._roots:
            # Evaluate a(root)
            val = sum(a[i] * root ** i for i in range(len(a)))
            norm *= val
        return float(np.real(norm))

    def trace_element(self, a: np.ndarray) -> float:
        """
        Trace Tr_{K/ℚ}(a) = Σ σᵢ(a) over all embeddings.
        """
        tr = 0.0
        for root in self._roots:
            val = sum(a[i] * root ** i for i in range(len(a)))
            tr += val
        return float(np.real(tr))

    @staticmethod
    def quadratic(d: int) -> 'NumberField':
        """
        Quadratic field ℚ(√d).

        Minimal polynomial: x² - d.
        """
        # Remove perfect square factors
        d_reduced = d
        for p in range(2, int(abs(d) ** 0.5) + 1):
            while d_reduced % (p * p) == 0:
                d_reduced //= (p * p)

        return NumberField(
            np.array([-d_reduced, 0, 1], dtype=float),
            name=f"Q(√{d_reduced})"
        )

    @staticmethod
    def cyclotomic(n: int) -> 'NumberField':
        """
        Cyclotomic field ℚ(ζₙ) where ζₙ = e^{2πi/n}.

        Minimal polynomial: n-th cyclotomic polynomial Φₙ(x).
        """
        # Compute cyclotomic polynomial via Möbius inversion
        coeffs = NumberField._cyclotomic_poly(n)
        return NumberField(coeffs, name=f"Q(ζ_{n})")

    @staticmethod
    def _cyclotomic_poly(n: int) -> np.ndarray:
        """Compute coefficients of the n-th cyclotomic polynomial."""
        # Start with x^n - 1, then divide by Φ_d for d | n, d < n
        # Simple implementation using roots of unity
        from math import gcd

        # Primitive n-th roots of unity
        roots = []
        for k in range(n):
            if gcd(k, n) == 1:
                roots.append(np.exp(2j * np.pi * k / n))

        # Build polynomial from roots
        poly = np.array([1.0], dtype=complex)
        for root in roots:
            poly = np.convolve(poly, np.array([1.0, -root]))

        # Should have integer (real) coefficients
        return np.real(poly[::-1])  # Reverse to get ascending order


# ============================================================================
# ALGEBRAIC INTEGER
# ============================================================================

class AlgebraicInteger:
    """
    An algebraic integer: root of a monic polynomial with integer coefficients.

    In a number field K = ℚ(α), algebraic integers form the ring O_K.
    Represented as a ℤ-linear combination of the integral basis.
    """

    def __init__(self, coefficients: np.ndarray, field: NumberField):
        """
        Args:
            coefficients: Integer coefficients in the power basis
                [a₀, a₁, ..., a_{n-1}] representing a₀ + a₁α + ... + a_{n-1}α^{n-1}.
            field: The ambient number field.
        """
        self.coeffs = np.array(coefficients, dtype=float)
        self.field = field

    def norm(self) -> float:
        """
        Norm N_{K/ℚ}(a) = Π σᵢ(a).

        For algebraic integers, the norm is always an integer.
        """
        return self.field.norm_element(self.coeffs)

    def trace(self) -> float:
        """
        Trace Tr_{K/ℚ}(a) = Σ σᵢ(a).

        For algebraic integers, the trace is always an integer.
        """
        return self.field.trace_element(self.coeffs)

    def minimal_polynomial(self) -> np.ndarray:
        """
        Compute the minimal polynomial of this algebraic integer over ℚ.

        The minimal polynomial divides the field's minimal polynomial.
        """
        n = self.field.degree()

        # Evaluate at all embeddings
        values = []
        for root in self.field.embeddings():
            val = sum(self.coeffs[i] * root ** i for i in range(len(self.coeffs)))
            values.append(val)

        # Build polynomial from these roots (some may be repeated)
        unique_vals = []
        for v in values:
            is_new = True
            for u in unique_vals:
                if abs(v - u) < 1e-8:
                    is_new = False
                    break
            if is_new:
                unique_vals.append(v)

        # Build minimal polynomial
        poly = np.array([1.0], dtype=complex)
        for root in unique_vals:
            poly = np.convolve(poly, np.array([1.0, -root]))

        # Round to integers
        result = np.real(poly[::-1])
        return np.round(result).astype(float)

    def __add__(self, other: 'AlgebraicInteger') -> 'AlgebraicInteger':
        return AlgebraicInteger(self.coeffs + other.coeffs, self.field)

    def __mul__(self, other: 'AlgebraicInteger') -> 'AlgebraicInteger':
        product = self.field.multiply_elements(self.coeffs, other.coeffs)
        return AlgebraicInteger(product, self.field)

    def __repr__(self):
        terms = []
        for i, c in enumerate(self.coeffs):
            if abs(c) < 1e-10:
                continue
            if i == 0:
                terms.append(f"{c:.0f}")
            elif i == 1:
                terms.append(f"{c:.0f}α")
            else:
                terms.append(f"{c:.0f}α^{i}")
        return " + ".join(terms) if terms else "0"


# ============================================================================
# RING OF INTEGERS
# ============================================================================

class RingOfIntegers:
    """
    Ring of integers O_K of a number field K.

    O_K = {α ∈ K : α is an algebraic integer}
        = {α ∈ K : the minimal polynomial of α has integer coefficients}

    For K = ℚ(√d):
        O_K = ℤ[√d]         if d ≡ 2, 3 (mod 4)
        O_K = ℤ[(1+√d)/2]   if d ≡ 1 (mod 4)
    """

    def __init__(self, field: NumberField):
        self.field = field
        self._integral_basis = self._compute_integral_basis()

    def _compute_integral_basis(self) -> list[np.ndarray]:
        """
        Compute an integral basis for O_K.

        Default: power basis {1, α, α², ..., α^{n-1}}.
        This equals O_K when the field discriminant equals
        the polynomial discriminant (monogenic case).
        """
        n = self.field.degree()
        basis = []
        for i in range(n):
            v = np.zeros(n)
            v[i] = 1.0
            basis.append(v)
        return basis

    def integral_basis(self) -> list[np.ndarray]:
        """Return the integral basis of O_K."""
        return [b.copy() for b in self._integral_basis]

    def is_element(self, alpha: np.ndarray) -> bool:
        """
        Check if α ∈ O_K by verifying its minimal polynomial has
        integer coefficients.
        """
        ai = AlgebraicInteger(alpha, self.field)
        min_poly = ai.minimal_polynomial()
        return all(abs(c - round(c)) < 1e-6 for c in min_poly)


# ============================================================================
# CLASS GROUP
# ============================================================================

class ClassGroup:
    """
    Ideal class group Cl(K) of a number field K.

    Cl(K) = (fractional ideals) / (principal ideals)
    h_K = |Cl(K)| is the class number.

    h_K = 1 ⟺ O_K is a PID (principal ideal domain)
           ⟺ O_K is a UFD (unique factorization domain)

    For imaginary quadratic fields ℚ(√-d), the class number
    can be computed via the Minkowski bound and quadratic forms.
    """

    def __init__(self, field: NumberField):
        self.field = field
        self._class_number = None
        self._representatives = None

    @staticmethod
    def compute(field: NumberField) -> 'ClassGroup':
        """Compute the class group of a number field."""
        cg = ClassGroup(field)
        cg._compute()
        return cg

    def _compute(self):
        """
        Compute class number using the Minkowski bound.

        Minkowski bound: every ideal class contains an ideal of norm ≤ M_K
        where M_K = (n!/nⁿ)(4/π)^{r₂} √|Δ_K|

        For small fields, enumerate ideals up to this bound.
        """
        n = self.field.degree()
        r1, r2 = self.field.signature()
        disc = abs(self.field.discriminant())

        if disc < 1e-10:
            self._class_number = 1
            return

        # Minkowski bound
        import math
        M = (math.factorial(n) / (n ** n)) * ((4 / np.pi) ** r2) * np.sqrt(disc)

        logger.info(f"Minkowski bound: {M:.2f}")

        # For quadratic fields, use the analytic formula
        if n == 2:
            self._class_number = self._quadratic_class_number()
        else:
            # General case: heuristic estimate
            # h ≈ √disc / (2π)^{r2} / R (where R is the regulator)
            self._class_number = max(1, int(round(np.sqrt(disc) / (2 * np.pi) ** r2)))

    def _quadratic_class_number(self) -> int:
        """
        Class number for quadratic fields ℚ(√d).

        For imaginary quadratic (d < 0): count reduced binary quadratic forms.
        For real quadratic (d > 0): use continued fraction for fundamental unit.
        """
        # Extract d from minimal polynomial x² - d
        d = -self.field.min_poly[0]  # min_poly = [-d, 0, 1]
        d = int(round(d))

        if d < 0:
            return self._imaginary_quadratic_class_number(d)
        else:
            return self._real_quadratic_class_number(d)

    def _imaginary_quadratic_class_number(self, d: int) -> int:
        """
        Class number of ℚ(√d) for d < 0.

        Count reduced binary quadratic forms of discriminant D.
        D = d if d ≡ 1 (mod 4), D = 4d otherwise.
        """
        if d % 4 == 1:
            D = d
        else:
            D = 4 * d

        D = abs(D)

        # Count reduced forms: |a| ≤ √(D/3), |b| ≤ a, a² ≤ D/3
        # Reduced form (a, b, c) with a > 0, |b| ≤ a, a ≤ c
        # and b ≥ 0 when a = c or |b| = a
        count = 0
        bound = int(np.sqrt(D / 3.0)) + 1

        for a in range(1, bound + 1):
            for b in range(-a, a + 1):
                # c = (b² + D) / (4a) for discriminant -D
                num = b * b + D
                if num % (4 * a) != 0:
                    continue
                c = num // (4 * a)

                if c < a:
                    continue

                # Reducedness conditions
                if abs(b) > a:
                    continue
                if a == c and b < 0:
                    continue
                if abs(b) == a and b < 0:
                    continue

                count += 1

        return max(1, count)

    def _real_quadratic_class_number(self, d: int) -> int:
        """
        Class number of ℚ(√d) for d > 0.

        Use the L-function approach: h = √D / (2 log ε) × L(1, χ_D)
        where ε is the fundamental unit and χ_D is the Kronecker symbol.
        Simplified: return 1 for small d (most common case).
        """
        # For many small d, h = 1
        # Full computation requires fundamental unit via continued fractions
        return 1

    def class_number(self) -> int:
        """Return the class number h_K."""
        if self._class_number is None:
            self._compute()
        return self._class_number

    def is_PID(self) -> bool:
        """O_K is a PID iff h_K = 1."""
        return self.class_number() == 1
