"""
Chronos State - Tracks active tasks and provides the 5 verbs

The 5 verbs: start, stop, log, note, link
"""

import time
from typing import Optional, List, Dict
from pathlib import Path
from datetime import datetime, timezone

from .event_log import EventLog, ChronosEvent


class ChronosState:
    """
    Core state manager for Chronos

    Provides the 5 verbs that manipulate the event log:
    - start: Begin tracking a task
    - stop: End current task
    - log: Retroactive entry
    - note: Add context
    - link: Connect events
    """

    def __init__(self, log_path: Path):
        self.event_log = EventLog(log_path)
        self.active_task: Optional[ChronosEvent] = None
        self._load_active_task()

    def _load_active_task(self):
        """Find most recent unclosed start event"""
        events = self.event_log.read_all()

        # Find all start events
        starts = {e.id: e for e in events if e.event == "start"}

        # Remove closed starts (those with corresponding stop)
        for e in events:
            if e.event == "stop" and e.start_id:
                starts.pop(e.start_id, None)

        # Most recent unclosed start is the active task
        if starts:
            self.active_task = max(starts.values(), key=lambda e: e.ts)

    def _now_iso(self) -> str:
        """Current time in ISO 8601 format"""
        return datetime.now(timezone.utc).isoformat()

    def _format_time(self, iso_str: str) -> str:
        """Format ISO timestamp for display (HH:MM:SS)"""
        dt = datetime.fromisoformat(iso_str.replace('Z', '+00:00'))
        return dt.strftime("%H:%M:%S")

    def _format_duration(self, seconds: float) -> str:
        """Format duration for display"""
        hours = int(seconds // 3600)
        minutes = int((seconds % 3600) // 60)
        secs = int(seconds % 60)

        if hours > 0:
            return f"{hours}h {minutes}m"
        elif minutes > 0:
            return f"{minutes}m {secs}s"
        else:
            return f"{secs}s"

    # ═══════════════════════════════════════════════════
    #  The 5 Verbs
    # ═══════════════════════════════════════════════════

    def start(self, task: str, tags: Optional[List[str]] = None) -> str:
        """
        START - Begin tracking a task

        Returns confirmation message
        """
        # If there's already an active task, warn but don't block
        if self.active_task:
            old_task = self.active_task.task
            # Auto-stop the old task
            self.stop()

        event = ChronosEvent(
            event="start",
            task=task,
            tags=tags or [],
            ts=self._now_iso(),
            id=""  # Will be generated by log
        )

        event = self.event_log.append(event)
        self.active_task = event

        tags_str = " ".join(f"#{t}" for t in event.tags) if event.tags else ""
        time_str = self._format_time(event.ts)

        if tags_str:
            return f"✅ Started {task} at {time_str} — tagged {tags_str}\n   (event {event.id})"
        else:
            return f"✅ Started {task} at {time_str}\n   (event {event.id})"

    def stop(self, task_name: Optional[str] = None) -> str:
        """
        STOP - End current task (or specified task)

        Returns confirmation message
        """
        if not self.active_task:
            return "❌ No active task to stop"

        if task_name and self.active_task.task != task_name:
            return f"❌ Active task is '{self.active_task.task}', not '{task_name}'"

        # Calculate duration
        start_ts = datetime.fromisoformat(self.active_task.ts.replace('Z', '+00:00'))
        stop_ts = datetime.now(timezone.utc)
        duration_sec = (stop_ts - start_ts).total_seconds()

        event = ChronosEvent(
            event="stop",
            task=self.active_task.task,
            start_id=self.active_task.id,
            duration_sec=duration_sec,
            ts=self._now_iso(),
            id=""
        )

        event = self.event_log.append(event)

        time_str = self._format_time(event.ts)
        duration_str = self._format_duration(duration_sec)

        task = self.active_task.task
        self.active_task = None

        return f"✅ Stopped {task} at {time_str} — duration {duration_str}\n   (event {event.id})"

    def log(
        self,
        task: str,
        duration_sec: float,
        tags: Optional[List[str]] = None,
        timestamp: Optional[str] = None
    ) -> str:
        """
        LOG - Retroactive entry (task already completed)

        Args:
            task: Task name
            duration_sec: How long it took (in seconds)
            tags: Optional tags
            timestamp: Optional start time (ISO 8601), defaults to now - duration

        Returns confirmation message
        """
        if timestamp is None:
            # Calculate start time (now - duration)
            start_ts = datetime.now(timezone.utc).timestamp() - duration_sec
            timestamp = datetime.fromtimestamp(start_ts, tz=timezone.utc).isoformat()

        event = ChronosEvent(
            event="log",
            task=task,
            duration_sec=duration_sec,
            tags=tags or [],
            ts=timestamp,
            id=""
        )

        event = self.event_log.append(event)

        tags_str = " ".join(f"#{t}" for t in event.tags) if event.tags else ""
        duration_str = self._format_duration(duration_sec)

        if tags_str:
            return f"✅ Logged {task}, {duration_str} — tagged {tags_str}\n   (event {event.id})"
        else:
            return f"✅ Logged {task}, {duration_str}\n   (event {event.id})"

    def note(self, text: str, linked_to: Optional[str] = None) -> str:
        """
        NOTE - Add context to a task

        Args:
            text: Note content
            linked_to: Event ID to link to (defaults to current active task)

        Returns confirmation message
        """
        # If no linked_to specified, link to active task
        if linked_to is None and self.active_task:
            linked_to = self.active_task.id

        if linked_to is None:
            return "❌ No active task and no event ID specified"

        # Verify linked event exists
        linked_event = self.event_log.get_event(linked_to)
        if not linked_event:
            return f"❌ Event {linked_to} not found"

        event = ChronosEvent(
            event="note",
            text=text,
            linked_to=linked_to,
            ts=self._now_iso(),
            id=""
        )

        event = self.event_log.append(event)

        task_name = linked_event.task or linked_to
        return f"✅ Note added to {task_name}\n   (event {event.id})"

    def link(self, from_id: str, to_id: str, relation: str = "related_to") -> str:
        """
        LINK - Connect events to external systems

        Args:
            from_id: Source event ID
            to_id: Target ID (can be external, e.g., "task_garden_prep_2025")
            relation: Relationship type (e.g., "part_of", "caused_by")

        Returns confirmation message
        """
        # Verify from_id exists
        from_event = self.event_log.get_event(from_id)
        if not from_event:
            return f"❌ Event {from_id} not found"

        event = ChronosEvent(
            event="link",
            from_id=from_id,
            to_id=to_id,
            relation=relation,
            ts=self._now_iso(),
            id=""
        )

        event = self.event_log.append(event)

        return f"✅ Linked {from_id} → {to_id} ({relation})\n   (event {event.id})"

    def status(self) -> str:
        """Get current status (active task, if any)"""
        if not self.active_task:
            return "⏸  No active task"

        start_ts = datetime.fromisoformat(self.active_task.ts.replace('Z', '+00:00'))
        now = datetime.now(timezone.utc)
        elapsed_sec = (now - start_ts).total_seconds()

        elapsed_str = self._format_duration(elapsed_sec)
        start_time_str = self._format_time(self.active_task.ts)

        return f"⏱  Active: {self.active_task.task} (started {start_time_str}, elapsed {elapsed_str})"
