"""
Symplectic Geometry Completion — GE4.6-4.7
==========================================

Moment maps, symplectic reduction, and cotangent bundle lifts.
Extends the existing mathematical_physics module (which has SymplecticManifold,
PoissonBracket, CanonicalTransformation) with the Marsden-Weinstein reduction
machinery and geometric mechanics infrastructure.

Classes:
    MomentMap: Conserved quantities from symmetry (Noether's theorem in symplectic form)
    SymplecticReduction: Marsden-Weinstein quotient construction
    CotangentBundle: Phase space lift from configuration to (position, momentum)

Mathematical Foundation:
    Symplectic form: omega = sum dp_i ^ dq_i (canonical)
    Moment map: mu: M -> g* satisfying Hamilton's equation for group actions
    Reduction: M_red = mu^{-1}(c) / G_c (level set modulo isotropy)
    Cotangent lift: T*Q with canonical symplectic structure

Author: Claude Code
Date: March 2026 (Math Module Expansion)
"""

import logging
from collections.abc import Callable
from dataclasses import dataclass

import numpy as np

logger = logging.getLogger(__name__)


@dataclass
class SymplecticForm:
    """
    Representation of a symplectic 2-form on a 2n-dimensional space.

    The standard form is omega = sum_{i=1}^n dp_i ^ dq_i,
    represented as a skew-symmetric matrix J.

    Attributes:
        matrix: Skew-symmetric matrix representing omega, shape (2n, 2n)
        dim: Phase space dimension 2n
    """
    matrix: np.ndarray
    dim: int

    @staticmethod
    def canonical(n: int) -> 'SymplecticForm':
        """Standard symplectic form J = [[0, I], [-I, 0]] for n degrees of freedom."""
        J = np.zeros((2 * n, 2 * n))
        J[:n, n:] = np.eye(n)
        J[n:, :n] = -np.eye(n)
        return SymplecticForm(matrix=J, dim=2 * n)

    def is_symplectic(self, tol: float = 1e-10) -> bool:
        """Check that matrix is skew-symmetric and non-degenerate."""
        skew = np.max(np.abs(self.matrix + self.matrix.T))
        det = abs(np.linalg.det(self.matrix))
        return skew < tol and det > tol

    def poisson_bracket(
        self, df: np.ndarray, dg: np.ndarray
    ) -> float:
        """
        Poisson bracket {f, g} = omega^{-1}(df, dg).

        Args:
            df: Gradient of f, shape (2n,)
            dg: Gradient of g, shape (2n,)

        Returns:
            Scalar value of {f, g}
        """
        omega_inv = np.linalg.inv(self.matrix)
        return float(df @ omega_inv @ dg)


class MomentMap:
    """
    Moment map mu: M -> g* for a symplectic group action.

    Given a Lie group G acting on (M, omega) by symplectomorphisms,
    the moment map encodes the conserved quantities (generalized momenta)
    associated with the symmetry via Noether's theorem.

    For each Lie algebra element xi in g, the Hamiltonian H_xi satisfies:
        dH_xi = iota_{xi_M} omega
    where xi_M is the vector field generated by xi.
    """

    def compute(
        self,
        symplectic_form: SymplecticForm,
        group_action: Callable[[np.ndarray, np.ndarray], np.ndarray],
        point: np.ndarray,
        generators: list[np.ndarray],
        dt: float = 1e-6,
    ) -> np.ndarray:
        """
        Compute the moment map at a point by numerical differentiation.

        For each generator xi_k, compute the infinitesimal vector field
        and find H_k such that dH_k = iota_{xi_M} omega.

        Args:
            symplectic_form: The symplectic form omega
            group_action: phi(g, z) -> z', maps group element and point to new point
            point: Phase space point z in R^{2n}
            generators: List of Lie algebra generators, each shape (dim_g,)
            dt: Step size for numerical differentiation

        Returns:
            Moment map values mu(z), shape (n_generators,)
        """
        omega = symplectic_form.matrix
        n = symplectic_form.dim
        mu = np.zeros(len(generators))

        for k, xi in enumerate(generators):
            # Compute infinitesimal action: xi_M(z) = d/dt|_{t=0} phi(exp(t*xi), z)
            xi_field = np.zeros(n)
            for i in range(n):
                e_i = np.zeros(n)
                e_i[i] = 1.0
                # Approximate directional derivative
                z_plus = point + dt * e_i
                z_minus = point - dt * e_i
                # The vector field at point
                v_plus = (group_action(dt * xi, z_plus) - z_plus) / dt
                v_minus = (group_action(dt * xi, z_minus) - z_minus) / dt
                xi_field[i] = (group_action(dt * xi, point) - point)[i] / dt

            # H_xi via contraction: dH_xi = iota_{xi_M} omega
            # H_xi(z) = omega(xi_M(z), z) for linear case
            mu[k] = xi_field @ omega @ point

        return mu

    def compute_angular_momentum(
        self, q: np.ndarray, p: np.ndarray
    ) -> np.ndarray:
        """
        Angular momentum as moment map for SO(3) action on T*R^3.

        L = q x p (cross product).

        Args:
            q: Position vector(s), shape (3,) or (n, 3)
            p: Momentum vector(s), shape (3,) or (n, 3)

        Returns:
            Angular momentum L = q x p, shape (3,) or (n, 3)
        """
        return np.cross(q, p)

    def compute_linear_momentum(self, p: np.ndarray) -> np.ndarray:
        """
        Linear momentum as moment map for translation action.

        The moment map for R^n acting on T*R^n by translation is
        simply the momentum: mu(q, p) = p.

        Args:
            p: Momentum vector(s)

        Returns:
            p (identity — translation symmetry yields momentum conservation)
        """
        return p.copy()

    def is_equivariant(
        self,
        symplectic_form: SymplecticForm,
        group_action: Callable,
        coadjoint_action: Callable,
        point: np.ndarray,
        generators: list[np.ndarray],
        group_elements: list[np.ndarray],
        dt: float = 1e-6,
        tol: float = 1e-4,
    ) -> bool:
        """
        Check equivariance: mu(phi_g(z)) = Ad*_g(mu(z)).

        An equivariant moment map intertwines the group action on M
        with the coadjoint action on g*.

        Args:
            symplectic_form: The symplectic form
            group_action: phi(g, z) -> z'
            coadjoint_action: Ad*(g, mu) -> mu'
            point: Test point z
            generators: Lie algebra generators
            group_elements: Group elements to test
            dt: Differentiation step
            tol: Tolerance for equivariance check

        Returns:
            True if equivariance holds at test point for all test elements
        """
        mu_z = self.compute(symplectic_form, group_action, point, generators, dt)

        for g in group_elements:
            gz = group_action(g, point)
            mu_gz = self.compute(symplectic_form, group_action, gz, generators, dt)
            ad_star_mu = coadjoint_action(g, mu_z)

            if np.linalg.norm(mu_gz - ad_star_mu) > tol:
                return False

        return True


class SymplecticReduction:
    """
    Marsden-Weinstein symplectic reduction.

    Given (M, omega) with moment map mu: M -> g*,
    the reduced space at level c is:
        M_c = mu^{-1}(c) / G_c

    where G_c is the isotropy subgroup of c under coadjoint action.
    The reduced space inherits a natural symplectic structure.
    """

    def reduce(
        self,
        manifold_points: np.ndarray,
        moment_values: np.ndarray,
        level: np.ndarray,
        tol: float = 1e-3,
    ) -> np.ndarray:
        """
        Compute the level set mu^{-1}(c) by selecting points near the level.

        This is the first step of reduction: finding the constraint surface.
        The quotient step requires identifying group orbits.

        Args:
            manifold_points: Phase space points, shape (n_points, 2n)
            moment_values: Moment map at each point, shape (n_points, dim_g)
            level: Target level c in g*, shape (dim_g,)
            tol: Tolerance for membership in level set

        Returns:
            Points in mu^{-1}(c), shape (n_selected, 2n)
        """
        distances = np.linalg.norm(moment_values - level[np.newaxis, :], axis=1)
        mask = distances < tol
        selected = manifold_points[mask]

        if len(selected) == 0:
            logger.warning(
                f"No points within tolerance {tol} of level {level}. "
                f"Minimum distance: {distances.min():.6f}"
            )

        return selected

    def quotient_by_orbits(
        self,
        level_set_points: np.ndarray,
        group_action: Callable[[np.ndarray, np.ndarray], np.ndarray],
        generators: list[np.ndarray],
        dt: float = 1e-4,
        tol: float = 1e-3,
    ) -> np.ndarray:
        """
        Quotient the level set by group orbits to obtain reduced space.

        Identifies orbits by flowing along infinitesimal group action vectors
        and clustering points on the same orbit.

        Args:
            level_set_points: Points on mu^{-1}(c), shape (n_points, 2n)
            group_action: phi(g, z) -> z'
            generators: Lie algebra generators for the group
            dt: Flow step for orbit identification
            tol: Tolerance for orbit membership

        Returns:
            Representative points (one per orbit), shape (n_orbits, 2n)
        """
        n_points = len(level_set_points)
        if n_points == 0:
            return np.empty((0, level_set_points.shape[1] if len(level_set_points.shape) > 1 else 0))

        visited = np.zeros(n_points, dtype=bool)
        representatives = []

        for i in range(n_points):
            if visited[i]:
                continue

            representatives.append(level_set_points[i])
            visited[i] = True

            # Flow along each generator to find orbit neighbors
            for xi in generators:
                flowed = group_action(dt * xi, level_set_points[i])
                dists = np.linalg.norm(level_set_points - flowed[np.newaxis, :], axis=1)
                visited[dists < tol] = True

        return np.array(representatives)

    def reduced_symplectic_form(
        self,
        symplectic_form: SymplecticForm,
        constraint_jacobian: np.ndarray,
    ) -> np.ndarray:
        """
        Compute the induced symplectic form on the reduced space.

        The reduced form omega_red is the pullback of omega to the
        level set, then projected onto the quotient. For linear constraints,
        this is computable via the null space of the constraint Jacobian.

        Args:
            symplectic_form: Original symplectic form omega
            constraint_jacobian: Jacobian of the constraints, shape (k, 2n)

        Returns:
            Reduced symplectic matrix, shape (2n-2k, 2n-2k)
        """
        omega = symplectic_form.matrix
        J = constraint_jacobian

        # Null space of J gives tangent directions to level set
        _, s, Vt = np.linalg.svd(J, full_matrices=True)
        rank = np.sum(s > 1e-10)
        null_space = Vt[rank:].T  # shape (2n, 2n-k)

        # Pull back omega to the null space
        omega_red = null_space.T @ omega @ null_space

        return omega_red


class CotangentBundle:
    """
    Cotangent bundle T*Q with canonical symplectic structure.

    For a configuration space Q (positions), the cotangent bundle
    T*Q = {(q, p) : q in Q, p in T*_q Q} is the natural phase space.
    It carries the canonical 1-form theta = p_i dq^i and symplectic
    form omega = -d(theta) = dq^i ^ dp_i.
    """

    @staticmethod
    def lift(
        configuration: np.ndarray,
        velocity: np.ndarray,
        mass_matrix: np.ndarray | None = None,
    ) -> tuple[np.ndarray, np.ndarray]:
        """
        Legendre transform: lift (q, q_dot) to (q, p) via p = M @ q_dot.

        Args:
            configuration: Position q, shape (n,) or (batch, n)
            velocity: Velocity q_dot, shape (n,) or (batch, n)
            mass_matrix: Mass/inertia matrix M, shape (n, n).
                         Defaults to identity (unit mass).

        Returns:
            (position, momentum) tuple, each same shape as input
        """
        q = np.asarray(configuration, dtype=float)
        v = np.asarray(velocity, dtype=float)

        if mass_matrix is None:
            p = v.copy()
        else:
            M = np.asarray(mass_matrix, dtype=float)
            if q.ndim == 1:
                p = M @ v
            else:
                p = (M @ v.T).T

        return q.copy(), p

    @staticmethod
    def inverse_lift(
        position: np.ndarray,
        momentum: np.ndarray,
        mass_matrix: np.ndarray | None = None,
    ) -> tuple[np.ndarray, np.ndarray]:
        """
        Inverse Legendre transform: (q, p) -> (q, q_dot) via q_dot = M^{-1} @ p.

        Args:
            position: Position q
            momentum: Momentum p
            mass_matrix: Mass matrix M (defaults to identity)

        Returns:
            (configuration, velocity) tuple
        """
        q = np.asarray(position, dtype=float)
        p = np.asarray(momentum, dtype=float)

        if mass_matrix is None:
            v = p.copy()
        else:
            M_inv = np.linalg.inv(mass_matrix)
            if q.ndim == 1:
                v = M_inv @ p
            else:
                v = (M_inv @ p.T).T

        return q.copy(), v

    @staticmethod
    def canonical_form(n_dof: int) -> SymplecticForm:
        """
        Canonical symplectic form on T*R^n.

        omega = sum dq^i ^ dp_i, represented as J = [[0, I], [-I, 0]].

        Args:
            n_dof: Number of degrees of freedom

        Returns:
            Canonical symplectic form
        """
        return SymplecticForm.canonical(n_dof)

    @staticmethod
    def hamiltonian_flow(
        hamiltonian_grad: Callable[[np.ndarray], np.ndarray],
        z0: np.ndarray,
        dt: float,
        n_steps: int,
        n_dof: int | None = None,
    ) -> np.ndarray:
        """
        Symplectic (Stormer-Verlet) integration of Hamilton's equations.

        dq/dt = dH/dp,  dp/dt = -dH/dq

        Uses the symplectic Euler method (preserves symplectic structure).

        Args:
            hamiltonian_grad: Returns gradient of H, shape (2n,).
                              First n components are dH/dq, last n are dH/dp.
            z0: Initial condition (q, p), shape (2n,)
            dt: Time step
            n_steps: Number of integration steps
            n_dof: Degrees of freedom (inferred from z0 if None)

        Returns:
            Trajectory, shape (n_steps + 1, 2n)
        """
        dim = len(z0)
        if n_dof is None:
            n_dof = dim // 2

        trajectory = np.zeros((n_steps + 1, dim))
        trajectory[0] = z0.copy()

        z = z0.copy()
        for step in range(n_steps):
            grad = hamiltonian_grad(z)
            dHdq = grad[:n_dof]
            dHdp = grad[n_dof:]

            # Symplectic Euler: half-step p, full-step q, half-step p
            z[n_dof:] -= 0.5 * dt * dHdq  # p half-step
            grad_mid = hamiltonian_grad(z)
            z[:n_dof] += dt * grad_mid[n_dof:]  # q full-step
            grad_new = hamiltonian_grad(z)
            z[n_dof:] -= 0.5 * dt * grad_new[:n_dof]  # p half-step

            trajectory[step + 1] = z.copy()

        return trajectory

    @staticmethod
    def cotangent_lift_map(
        config_map: Callable[[np.ndarray], np.ndarray],
        config_jacobian: Callable[[np.ndarray], np.ndarray],
        q: np.ndarray,
        p: np.ndarray,
    ) -> tuple[np.ndarray, np.ndarray]:
        """
        Cotangent lift of a configuration space map.

        Given phi: Q -> Q', the cotangent lift T*phi: T*Q' -> T*Q is
        (phi(q), (D phi(q))^{-T} p).

        Args:
            config_map: Map phi: Q -> Q'
            config_jacobian: Jacobian D phi(q), returns shape (n, n)
            q: Position in Q
            p: Momentum in T*_q Q

        Returns:
            (phi(q), (D phi)^{-T} p) — lifted phase space point
        """
        q_new = config_map(q)
        J = config_jacobian(q)
        p_new = np.linalg.solve(J.T, p)
        return q_new, p_new
