/**
 * Store Slices
 *
 * Modular state slices for HoloLoom components.
 */

export {
  createTimelineSlice,
  WEAVING_STAGES,
  STAGE_DISPLAY_NAMES,
  selectStageTiming,
  selectActiveStage,
  selectTokenRate,
  selectTokenRateHistory,
  selectTotalTokens,
  selectIsTimelineExpanded,
  selectOrderedStages,
  selectCompletedStagesCount,
  selectProgress,
  selectTotalElapsedTime,
  selectEstimatedRemainingTime,
  selectAverageTokenRate,
  type TimelineState,
  type TimelineActions,
  type TimelineSlice,
  type StageTimingData,
  type StageStatus,
  type TokenRateEntry,
} from './timelineSlice';

export {
  createGraphSlice,
  selectNodes,
  selectEdges,
  selectSelectedNode,
  selectHoveredNode,
  selectQueryNode,
  selectViewport,
  selectLayout,
  selectRetrievalPath,
  selectIsLoading,
  selectError,
  selectNodesArray,
  selectEdgesArray,
  selectNodeCount,
  selectEdgeCount,
  selectActiveNodes,
  selectPathNodes,
  selectNodeNeighbors,
  type GraphState,
  type GraphActions,
  type GraphSlice,
  type GraphNode,
  type GraphEdge,
  type GraphNodeType,
  type GraphEdgeType,
  type ActivationEvent,
  type RetrievalPath,
  type GraphViewport,
  type LayoutSettings,
} from './graphSlice';

export {
  createLandscapeSlice,
  selectGrid,
  selectGridDimensions,
  selectAxisLabels,
  selectValueRange,
  selectHighlightedCells,
  selectHoveredCellInfo,
  selectSelectedCellInfo,
  selectViewSettings,
  selectIsLandscapeLoading,
  selectLandscapeError,
  selectAnimationProgress,
  selectIsCellHighlighted,
  selectCellHighlight,
  selectHighConfidenceCells,
  selectLowConfidenceCells,
  selectGridStatistics,
  type LandscapeState,
  type LandscapeActions,
  type LandscapeSlice,
  type GridCell,
  type HighlightReason,
  type HighlightedCell,
  type LandscapeViewMode,
  type ColorScale,
} from './landscapeSlice';

export {
  createCollaborationSlice,
  selectCurrentUser,
  selectOnlineUsers,
  selectOtherUsers,
  selectUserById,
  selectOtherCursors,
  selectSession,
  selectIsCollaborating,
  selectAnnotationsForTarget,
  selectReactionsForTarget,
  selectReactionCounts,
  selectHasUserReacted,
  selectSyncStatus,
  selectCollaborationSettings,
  selectIsConnected,
  selectUsersFocusedOnNode,
  selectUnresolvedAnnotations,
  selectAnnotationCounts,
  type CollaborationState,
  type CollaborationActions,
  type CollaborationSlice,
  type UserPresence,
  type CursorPosition,
  type UserFocus,
  type Annotation,
  type AnnotationReply,
  type Reaction,
  type CollaborativeSession,
  type SyncStatus,
} from './collaborationSlice';
