import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Auto-generated sidebars for API documentation.
 * Pulls README.md files from HoloLoom/ subdirectories.
 */
const sidebars: SidebarsConfig = {
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Use the root of the api docs path (../HoloLoom)
    },
  ],
};

export default sidebars;
