import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Auto-generated sidebars for main documentation.
 * Uses folder structure from ../docs/
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Home',
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'getting-started'},
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {type: 'autogenerated', dirName: 'guides'},
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        {type: 'autogenerated', dirName: 'architecture'},
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      items: [
        {type: 'autogenerated', dirName: 'examples'},
      ],
    },
    {
      type: 'category',
      label: 'Features',
      items: [
        {type: 'autogenerated', dirName: 'features'},
      ],
    },
    {
      type: 'category',
      label: 'Research',
      items: [
        {type: 'autogenerated', dirName: 'research'},
      ],
    },
    {
      type: 'category',
      label: 'Safety',
      items: [
        {type: 'autogenerated', dirName: 'safety'},
      ],
    },
  ],
};

export default sidebars;
