import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Auto-generated sidebars for archive documentation.
 * Pulls from ../archive/
 */
const sidebars: SidebarsConfig = {
  archiveSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Use the root of the archive docs path (../archive)
    },
  ],
};

export default sidebars;
