apiVersion: v1
kind: Namespace
metadata:
  name: zerog-prod
  labels:
    name: zerog-prod
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: zerog-staging
  labels:
    name: zerog-staging
    environment: staging
