"""
Quotient & Product Spaces — Topological Space Constructions
=============================================================

Fundamental constructions in point-set topology: quotient spaces
(collapsing equivalence classes), product topologies (Cartesian
products with box/product topology), and coproducts (disjoint unions).

Core Concepts:
- Quotient Space: X/~ identifies equivalent points, inherits quotient topology
- Product Topology: Π Xᵢ with topology generated by cylinder sets
- Coproduct (Disjoint Union): ⊔ Xᵢ with each component open

Mathematical Foundation:
Quotient: U ⊆ X/~ is open iff π⁻¹(U) is open in X (final topology)
Product: Generated by {π_i⁻¹(U_i) : U_i open in X_i} (coarsest topology)
Tychonoff: Product of compact spaces is compact (AC required for infinite products)

Applications to Warp Space:
- Quotient spaces for equivalence class identification in embeddings
- Product topology for joint state spaces in multi-modal reasoning
- Coproduct for disjoint memory domain union

Author: Claude Code
Date: March 2026 (Math Module Expansion)
"""

import logging
from collections.abc import Callable
from dataclasses import dataclass
from typing import Any

logger = logging.getLogger(__name__)


# ============================================================================
# DATA STRUCTURES
# ============================================================================

@dataclass
class TopologicalSpace:
    """Finite topological space represented by point set and open sets.

    Attributes:
        points: Set of point indices.
        open_sets: Collection of open sets (each a frozenset of point indices).
    """
    points: set[int]
    open_sets: set[frozenset]

    def is_open(self, subset: set[int]) -> bool:
        """Check if a subset is open."""
        return frozenset(subset) in self.open_sets

    def is_closed(self, subset: set[int]) -> bool:
        """Check if a subset is closed (complement is open)."""
        complement = self.points - subset
        return frozenset(complement) in self.open_sets

    @property
    def is_valid_topology(self) -> bool:
        """Verify topology axioms: empty and full set open, closed under union and finite intersection."""
        if frozenset() not in self.open_sets:
            return False
        if frozenset(self.points) not in self.open_sets:
            return False
        # Check pairwise intersections
        opens = list(self.open_sets)
        for i in range(len(opens)):
            for j in range(i + 1, len(opens)):
                if opens[i] & opens[j] not in self.open_sets:
                    return False
        # Check pairwise unions
        for i in range(len(opens)):
            for j in range(i + 1, len(opens)):
                if opens[i] | opens[j] not in self.open_sets:
                    return False
        return True

    @classmethod
    def discrete(cls, n: int) -> 'TopologicalSpace':
        """Create discrete topology (all subsets open)."""
        points = set(range(n))
        open_sets = set()
        # Generate all subsets
        for mask in range(2 ** n):
            subset = frozenset(i for i in range(n) if mask & (1 << i))
            open_sets.add(subset)
        return cls(points=points, open_sets=open_sets)

    @classmethod
    def indiscrete(cls, n: int) -> 'TopologicalSpace':
        """Create indiscrete topology (only empty and full set open)."""
        points = set(range(n))
        open_sets = {frozenset(), frozenset(points)}
        return cls(points=points, open_sets=open_sets)


# ============================================================================
# QUOTIENT SPACE
# ============================================================================

class QuotientSpace:
    """Quotient topological space X/~.

    Given a topological space X and an equivalence relation ~, the
    quotient space identifies equivalent points. The quotient topology
    is the finest topology making the projection π continuous.

    U ⊆ X/~ is open iff π⁻¹(U) is open in X.

    Example:
        >>> X = TopologicalSpace.discrete(4)
        >>> # Identify points 0≡1 and 2≡3
        >>> equiv = lambda a, b: a // 2 == b // 2
        >>> Q = QuotientSpace(X, equiv)
        >>> Q.project(0) == Q.project(1)  # True
    """

    def __init__(self, space: TopologicalSpace, equivalence: Callable[[int, int], bool]):
        """Initialize quotient space.

        Args:
            space: Base topological space X.
            equivalence: Equivalence relation (a, b) -> bool.
        """
        self.space = space
        self.equivalence = equivalence
        self._classes: dict[int, int] = {}  # point -> class representative
        self._compute_classes()

    def _compute_classes(self) -> None:
        """Compute equivalence classes using union-find."""
        parent: dict[int, int] = {p: p for p in self.space.points}

        def find(x: int) -> int:
            while parent[x] != x:
                parent[x] = parent[parent[x]]
                x = parent[x]
            return x

        def union(x: int, y: int) -> None:
            px, py = find(x), find(y)
            if px != py:
                parent[px] = py

        points = sorted(self.space.points)
        for i, a in enumerate(points):
            for b in points[i + 1:]:
                if self.equivalence(a, b):
                    union(a, b)

        self._classes = {p: find(p) for p in self.space.points}

    def project(self, point: int) -> int:
        """Project point to its equivalence class representative.

        Args:
            point: Point in X.

        Returns:
            Representative of [point] in X/~.
        """
        return self._classes.get(point, point)

    @property
    def quotient_points(self) -> set[int]:
        """Set of equivalence class representatives."""
        return set(self._classes.values())

    @property
    def equivalence_classes(self) -> dict[int, set[int]]:
        """Map from representative to equivalence class members."""
        classes: dict[int, set[int]] = {}
        for point, rep in self._classes.items():
            if rep not in classes:
                classes[rep] = set()
            classes[rep].add(point)
        return classes

    def quotient_topology(self) -> TopologicalSpace:
        """Compute the quotient topology.

        U ⊆ X/~ is open iff π⁻¹(U) is open in X.

        Returns:
            Quotient topological space.
        """
        q_points = self.quotient_points
        q_open: set[frozenset] = set()

        # Check all subsets of quotient points
        q_list = sorted(q_points)
        n = len(q_list)

        for mask in range(2 ** n):
            subset = frozenset(q_list[i] for i in range(n) if mask & (1 << i))
            # Compute preimage
            preimage = set()
            for point, rep in self._classes.items():
                if rep in subset:
                    preimage.add(point)
            # Check if preimage is open in X
            if frozenset(preimage) in self.space.open_sets:
                q_open.add(subset)

        return TopologicalSpace(points=q_points, open_sets=q_open)

    def is_hausdorff(self) -> bool:
        """Check if quotient space is Hausdorff (T2).

        A space is Hausdorff if distinct points have disjoint open
        neighborhoods.
        """
        qt = self.quotient_topology()
        q_points = sorted(qt.points)

        for i, p in enumerate(q_points):
            for q in q_points[i + 1:]:
                # Find disjoint open neighborhoods
                found = False
                for U in qt.open_sets:
                    if p not in U:
                        continue
                    for V in qt.open_sets:
                        if q not in V:
                            continue
                        if not (U & V):  # Disjoint
                            found = True
                            break
                    if found:
                        break
                if not found:
                    return False
        return True

    def lift_function(self, f: Callable[[int], Any]) -> Callable[[int], Any] | None:
        """Check if function f on X descends to quotient.

        f descends iff f(a) = f(b) whenever a ~ b.

        Args:
            f: Function on X.

        Returns:
            Descended function on X/~ if it exists, else None.
        """
        classes = self.equivalence_classes
        for rep, members in classes.items():
            values = {f(m) for m in members}
            if len(values) > 1:
                return None

        def descended(q_point: int) -> Any:
            return f(q_point)

        return descended


# ============================================================================
# PRODUCT TOPOLOGY
# ============================================================================

class ProductTopology:
    """Product of finitely many topological spaces.

    The product topology on Π Xᵢ is generated by sets of the form
    π_i⁻¹(U_i) = X₁ × ... × U_i × ... × Xₙ where U_i is open in Xᵢ.

    Example:
        >>> X = TopologicalSpace.discrete(3)
        >>> Y = TopologicalSpace.discrete(2)
        >>> prod = ProductTopology([X, Y])
        >>> prod.project((1, 0), 0)  # Project to first factor: 1
    """

    def __init__(self, spaces: list[TopologicalSpace]):
        """Initialize product topology.

        Args:
            spaces: List of factor spaces.
        """
        self.spaces = spaces
        self.n_factors = len(spaces)

    def project(self, point: tuple[int, ...], index: int) -> int:
        """Project product point to factor.

        Args:
            point: Point in product space (x₁, ..., xₙ).
            index: Factor index to project onto.

        Returns:
            Projected coordinate.
        """
        return point[index]

    def inject(self, value: int, index: int, base_point: tuple[int, ...] | None = None) -> tuple[int, ...]:
        """Inject into product at given factor.

        Creates a product point with the given value at the specified
        index and base_point values elsewhere.

        Args:
            value: Value to inject.
            index: Factor index.
            base_point: Values for other factors (defaults to min element).

        Returns:
            Point in product space.
        """
        if base_point is None:
            base_point = tuple(min(s.points) for s in self.spaces)

        result = list(base_point)
        result[index] = value
        return tuple(result)

    @property
    def product_points(self) -> set[tuple[int, ...]]:
        """All points in the product space."""
        if not self.spaces:
            return set()

        result = {(p,) for p in self.spaces[0].points}
        for space in self.spaces[1:]:
            new_result = set()
            for existing in result:
                for p in space.points:
                    new_result.add(existing + (p,))
            result = new_result

        return result

    def product_topology_space(self) -> TopologicalSpace:
        """Compute the product topological space explicitly.

        Warning: exponential in number of factors and points.
        Only practical for small spaces.

        Returns:
            Product topological space.
        """
        # Map product points to integer indices
        prod_points = sorted(self.product_points)
        point_to_idx = {p: i for i, p in enumerate(prod_points)}
        idx_points = set(range(len(prod_points)))

        # Generate basis: cylinder sets π_i⁻¹(U_i)
        basis: set[frozenset] = set()
        basis.add(frozenset())  # Empty set
        basis.add(frozenset(idx_points))  # Full set

        for i, space in enumerate(self.spaces):
            for U in space.open_sets:
                cylinder = frozenset(
                    point_to_idx[p] for p in prod_points
                    if p[i] in U
                )
                basis.add(cylinder)

        # Close under finite intersection and arbitrary union
        topology = set(basis)
        changed = True
        while changed:
            changed = False
            new_sets = set()
            topo_list = list(topology)
            for a in topo_list:
                for b in topo_list:
                    inter = a & b
                    union = a | b
                    if inter not in topology:
                        new_sets.add(inter)
                    if union not in topology:
                        new_sets.add(union)
            if new_sets:
                topology.update(new_sets)
                changed = True

        return TopologicalSpace(points=idx_points, open_sets=topology)

    def is_connected(self) -> bool:
        """Product is connected iff all factors are connected.

        A space is connected if it cannot be written as union of
        two disjoint non-empty open sets.
        """
        for space in self.spaces:
            if not self._is_space_connected(space):
                return False
        return True

    @staticmethod
    def _is_space_connected(space: TopologicalSpace) -> bool:
        """Check if a single space is connected."""
        for U in space.open_sets:
            if not U or U == frozenset(space.points):
                continue
            complement = frozenset(space.points) - U
            if complement in space.open_sets:
                return False
        return True


# ============================================================================
# COPRODUCT TOPOLOGY (DISJOINT UNION)
# ============================================================================

class CoproductTopology:
    """Coproduct (disjoint union) of topological spaces.

    The disjoint union ⊔ Xᵢ has the coproduct topology where
    U ⊆ ⊔ Xᵢ is open iff U ∩ Xᵢ is open in Xᵢ for all i.
    Each component Xᵢ is both open and closed (clopen).

    Example:
        >>> X = TopologicalSpace.discrete(3)
        >>> Y = TopologicalSpace.discrete(2)
        >>> coprod = CoproductTopology([X, Y])
        >>> result = coprod.disjoint_union()
    """

    def __init__(self, spaces: list[TopologicalSpace]):
        """Initialize coproduct.

        Args:
            spaces: List of spaces to take disjoint union of.
        """
        self.spaces = spaces
        self.n_components = len(spaces)
        self._offsets: list[int] = []
        offset = 0
        for space in spaces:
            self._offsets.append(offset)
            offset += len(space.points)

    def disjoint_union(self) -> TopologicalSpace:
        """Compute the disjoint union topology.

        Points are re-indexed: space i's point j becomes offset_i + j.

        Returns:
            Disjoint union topological space.
        """
        all_points: set[int] = set()
        all_open: set[frozenset] = set()

        # Re-index points for each component
        point_maps: list[dict[int, int]] = []
        for i, space in enumerate(self.spaces):
            pmap = {}
            for p in space.points:
                new_idx = self._offsets[i] + p
                pmap[p] = new_idx
                all_points.add(new_idx)
            point_maps.append(pmap)

        # Generate open sets
        # Each combination of open sets from components is open
        component_opens = []
        for i, space in enumerate(self.spaces):
            translated = []
            for U in space.open_sets:
                translated.append(frozenset(point_maps[i][p] for p in U))
            component_opens.append(translated)

        # Build by unions of open sets from each component
        all_open.add(frozenset())
        current = [frozenset()]

        for i in range(self.n_components):
            new_sets = set()
            for existing in current:
                for U_i in component_opens[i]:
                    new_sets.add(existing | U_i)
            current = list(new_sets)
            all_open.update(new_sets)

        return TopologicalSpace(points=all_points, open_sets=all_open)

    def component_of(self, point: int) -> int:
        """Determine which component a point belongs to.

        Args:
            point: Point index in the disjoint union.

        Returns:
            Component index.
        """
        for i in range(self.n_components - 1, -1, -1):
            if point >= self._offsets[i]:
                return i
        return 0

    def inclusion(self, component: int, point: int) -> int:
        """Map a point from component space to disjoint union.

        Args:
            component: Component index.
            point: Point in component space.

        Returns:
            Point index in disjoint union.
        """
        return self._offsets[component] + point

    def fold_map(self, target: TopologicalSpace, maps: list[Callable[[int], int]]) -> Callable[[int], int]:
        """Universal property: maps from each component induce a map from coproduct.

        Given fᵢ: Xᵢ → Y for each i, there is a unique f: ⊔Xᵢ → Y.

        Args:
            target: Target space Y.
            maps: List of functions fᵢ: Xᵢ → Y.

        Returns:
            Combined function f: ⊔Xᵢ → Y.
        """
        offsets = self._offsets
        spaces = self.spaces

        def combined(point: int) -> int:
            comp = self.component_of(point)
            local_point = point - offsets[comp]
            return maps[comp](local_point)

        return combined
